### ISSUE TITLE
Allow Imports of .gitignore templates

### ISSUE THREAD

**Issue by squashd** [SQUASHD/gogi#11]
Sometimes you find a nice gitignore or you have one ready you want easily accessible

Task:
- Allow for imports of gitignore files
- There should be no naming conflicts
- Optional flag to set as base

**Comment by SQUASHD** [comment]
Having thought about this: due to how easy it is to simply copy and paste, this would simply be bloat. Allowing for curling or getting template resources could be interesting but is not within the current scope of the project
